//@ui5-bundle socios/Component-preload.js
sap.ui.predefine("socios/Component", ["sap/ui/core/UIComponent","socios/model/models"],(e,t)=>{"use strict";return e.extend("socios.Component",{metadata:{manifest:"json",interfaces:["sap.ui.core.IAsyncContentCreation"]},init(){e.prototype.init.apply(this,arguments);this.setModel(t.createDeviceModel(),"device");this.getRouter().initialize()}})});
sap.ui.predefine("socios/controller/App.controller", ["sap/ui/core/mvc/Controller"],e=>{"use strict";return e.extend("socios.controller.App",{onInit(){}})});
sap.ui.predefine("socios/controller/Main.controller", ["sap/ui/core/mvc/Controller"],e=>{"use strict";return e.extend("socios.controller.Main",{onInit(){}})});
sap.ui.predefine("socios/model/models", ["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
sap.ui.require.preload({
	"socios/i18n/i18n.properties":'# This is the resource bundle for socios\n\n#Texts for manifest.json\n\n#XTIT: Application name\nappTitle=GesSocios \n\n#YDES: Application description\nappDescription=An SAP Fiori application.\r\n#XTIT: Main view title\ntitle=GesSocios ',
	"socios/manifest.json":'{"_version":"1.60.0","sap.app":{"id":"socios","type":"application","i18n":{"bundleUrl":"i18n/i18n.properties","supportedLocales":[""]},"applicationVersion":{"version":"0.0.1"},"title":"{{appTitle}}","description":"{{appDescription}}","resources":"resources.json","sourceTemplate":{"id":"@sap/generator-fiori:basic","version":"1.20.0","toolsId":"7ee52458-de39-486c-9ab1-7a097d8cef8f"}},"sap.ui":{"technology":"UI5","icons":{"icon":"","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":true,"dependencies":{"minUI5Version":"1.120.0","libs":{"sap.m":{},"sap.ui.core":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"socios.i18n.i18n","supportedLocales":[""]}}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","controlAggregation":"pages","controlId":"app","transition":"slide","type":"View","viewType":"XML","path":"socios.view","async":true,"viewPath":"socios.view"},"routes":[{"name":"RouteMain","pattern":":?query:","target":["TargetMain"]}],"targets":{"TargetMain":{"id":"Main","name":"Main"}}},"rootView":{"viewName":"socios.view.App","type":"XML","id":"App","async":true},"flexBundle":false}}',
	"socios/view/App.view.xml":'<mvc:View controllerName="socios.controller.App"\n    displayBlock="true"\n    xmlns:mvc="sap.ui.core.mvc"\n    xmlns="sap.m"><App id="app"></App></mvc:View>',
	"socios/view/Main.view.xml":'<mvc:View controllerName="socios.controller.Main"\n    xmlns:mvc="sap.ui.core.mvc"\n    xmlns="sap.m"><Page id="page" title="{i18n>title}"></Page></mvc:View>'
});
//# sourceMappingURL=Component-preload.js.map
